version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: always
    volumes:
      - ./src:/var/www/html

  pg:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker1234

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'docker1234'
      ACCEPT_EULA: 'Y'
    volumes:
      - mssql-data:/var/opt/mssql/data

volumes:
  pg-data:
  mssql-data:
